cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "black"
brew "deno"
brew "flake8"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "howdoi"
brew "jupyter"
brew "mas"
brew "mypy"
brew "nmap"
brew "node"
brew "openssh"
brew "pandoc"
brew "pinentry-mac"
brew "pipenv"
brew "pre-commit"
brew "python"
brew "r"
brew "ruby"
brew "shellcheck"
brew "shfmt"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "alfred"
cask "backblaze"
cask "brave-browser"
cask "docker"
cask "firefox-developer-edition"
cask "insomnia"
cask "iterm2"
cask "keybase"
cask "postgres"
cask "postico"
cask "protonvpn"
cask "rstudio"
cask "visual-studio-code"
cask "zotero"
mas "1password", id: 1333542190
mas "bear", id: 1091189122
mas "todoist", id: 585829637
